/* Generated by scripts/build-offline.mjs. Changes are overwritten by npm run build. */
'use strict';
const VERSION = "3b0df50e9fd9f4baa4a3";
const ASSETS = [
  "./apple-touch-icon.png",
  "./art/archive.png",
  "./art/archivist.png",
  "./art/explorer-alpha.png",
  "./art/species.png",
  "./art/verge.png",
  "./art/witness.png",
  "./assets/AI-COMPANION-Cla8xmjz.md",
  "./assets/ai-companion-D_dP-X9O.js",
  "./assets/app-BUVDO53l.css",
  "./assets/app-D2o_oVLG.js",
  "./assets/app-sg5m8bdE.css",
  "./assets/app-vzSeFNPf.js",
  "./assets/index-CrBv7lHg.js",
  "./assets/main-Bw2R7toq.js",
  "./assets/main-DOIRNVEH.css",
  "./assets/offline-Ba0H51YH.js",
  "./assets/peer-transport-D0OwxzSl.js",
  "./assets/random-DuC4XlEt.js",
  "./assets/store-CB4IUYNL.css",
  "./assets/store-Ccd2tGYC.js",
  "./audio/LICENSE.md",
  "./audio/PROVENANCE.json",
  "./audio/birds-9f9954e46768.mp3",
  "./audio/fire-488bab2d953a.mp3",
  "./audio/foley-662704446fff.wav",
  "./audio/insects-f5506a429b52.mp3",
  "./audio/water-29c7c1bd9902.mp3",
  "./audio/wind-145d6f104306.mp3",
  "./favicon-32.png",
  "./fonts/Caveat.ttf",
  "./fonts/OFL-Caveat.txt",
  "./icon-192.png",
  "./icon-512.png",
  "./icon-maskable-192.png",
  "./icon-maskable-512.png",
  "./icon.svg",
  "./index.html",
  "./manifest.webmanifest",
  "./release.json"
];
const SCOPE = new URL(self.registration.scope);
const PREFIX = 'verso-offline:' + encodeURIComponent(SCOPE.href) + ':';
const CACHE = PREFIX + VERSION;
const URLS = new Set(ASSETS.map(asset => new URL(asset, SCOPE).href));
const INDEX = new URL('./index.html', SCOPE).href;

function inScope(url) {
  return url.origin === SCOPE.origin && url.pathname.startsWith(SCOPE.pathname);
}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is atomic: a failed asset keeps this update from replacing a
    // complete working version. Redirects cannot introduce external assets.
    await cache.addAll([...URLS].map(url => new Request(url, {
      cache: 'reload', mode: 'same-origin', redirect: 'error',
    })));
  })());
  // Let an existing version finish its sessions; never force a page reload.
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(name => name.startsWith(PREFIX) && name !== CACHE)
      .map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});

async function navigation(request) {
  let response;
  try {
    response = await fetch(request);
    if (response.ok) return response;
  } catch { /* An installed app can open its cached entry while offline. */ }
  const cache = await caches.open(CACHE);
  return await cache.match(INDEX) || response || new Response('Verso is not available offline yet.', {
    status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}

async function asset(request, key) {
  const cache = await caches.open(CACHE);
  const stored = await cache.match(key);
  if (stored) return stored;
  const response = await fetch(request);
  if (response.ok && response.type !== 'opaque' && inScope(new URL(response.url || request.url))) {
    await cache.put(key, response.clone());
  }
  return response;
}

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (!inScope(url)) return;
  if (request.mode === 'navigate') {
    event.respondWith(navigation(request));
    return;
  }
  // Only the build's known static assets enter the cache, never API calls or
  // another application sharing this origin. Queries do not duplicate assets.
  url.search = '';
  url.hash = '';
  if (URLS.has(url.href)) event.respondWith(asset(request, url.href));
});
