/* Generated by scripts/build-offline.mjs. Changes are overwritten by npm run build. */
'use strict';
const VERSION = "2cb83e93797ae90d0db9";
const ASSETS = [
  "./art/archive.png",
  "./art/archivist.png",
  "./art/explorer-alpha.png",
  "./art/species.png",
  "./art/verge.png",
  "./art/witness.png",
  "./assets/app-CxKixEoO.js",
  "./assets/app-DrgXZaZt.css",
  "./assets/app-j0zfO6gz.js",
  "./assets/app-sg5m8bdE.css",
  "./assets/index-FeIZ1n_U.js",
  "./assets/main-CBXv9jq3.js",
  "./assets/main-DOIRNVEH.css",
  "./assets/offline-DCE4YSoD.js",
  "./assets/peer-transport-BB1VMhiR.js",
  "./assets/random-DuC4XlEt.js",
  "./assets/store-CB4IUYNL.css",
  "./assets/store-CDVJqUZT.js",
  "./fonts/Caveat.ttf",
  "./fonts/OFL-Caveat.txt",
  "./icon.svg",
  "./index.html",
  "./manifest.webmanifest"
];
const SCOPE = new URL(self.registration.scope);
const PREFIX = 'verso-offline:' + encodeURIComponent(SCOPE.href) + ':';
const CACHE = PREFIX + VERSION;
const URLS = new Set(ASSETS.map(asset => new URL(asset, SCOPE).href));
const INDEX = new URL('./index.html', SCOPE).href;

function inScope(url) {
  return url.origin === SCOPE.origin && url.pathname.startsWith(SCOPE.pathname);
}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is atomic: a failed asset keeps this update from replacing a
    // complete working version. Redirects cannot introduce external assets.
    await cache.addAll([...URLS].map(url => new Request(url, {
      cache: 'reload', mode: 'same-origin', redirect: 'error',
    })));
  })());
  // Let an existing version finish its sessions; never force a page reload.
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(name => name.startsWith(PREFIX) && name !== CACHE)
      .map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});

async function navigation(request) {
  let response;
  try {
    response = await fetch(request);
    if (response.ok) return response;
  } catch { /* An installed app can open its cached entry while offline. */ }
  const cache = await caches.open(CACHE);
  return await cache.match(INDEX) || response || new Response('Verso is not available offline yet.', {
    status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}

async function asset(request, key) {
  const cache = await caches.open(CACHE);
  const stored = await cache.match(key);
  if (stored) return stored;
  const response = await fetch(request);
  if (response.ok && response.type !== 'opaque' && inScope(new URL(response.url || request.url))) {
    await cache.put(key, response.clone());
  }
  return response;
}

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (!inScope(url)) return;
  if (request.mode === 'navigate') {
    event.respondWith(navigation(request));
    return;
  }
  // Only the build's known static assets enter the cache, never API calls or
  // another application sharing this origin. Queries do not duplicate assets.
  url.search = '';
  url.hash = '';
  if (URLS.has(url.href)) event.respondWith(asset(request, url.href));
});
