import { createHash } from 'node:crypto';
import { readdir, readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';
import { fileURLToPath } from 'node:url';

/** Discover the finished static app; generated workers and source maps are not assets. */
async function discover(directory, prefix = '') {
  const files = [];
  for (const entry of await readdir(directory, { withFileTypes: true })) {
    if (entry.name.startsWith('.') || entry.name === 'sw.js' || entry.name.endsWith('.map'))
      continue;
    const relative = prefix ? `${prefix}/${entry.name}` : entry.name;
    if (entry.isSymbolicLink())
      throw new Error(`Offline assets cannot be symbolic links: ${relative}`);
    if (entry.isDirectory())
      files.push(...(await discover(path.join(directory, entry.name), relative)));
    else if (entry.isFile()) files.push(relative);
  }
  return files.sort();
}

/** Build a content-versioned worker without introducing a runtime dependency. */
export async function buildOffline(
  directory = fileURLToPath(new URL('../dist/', import.meta.url)),
) {
  const files = await discover(directory);
  for (const required of ['index.html', 'manifest.webmanifest', 'icon.svg']) {
    if (!files.includes(required)) throw new Error(`Offline build is missing ${required}`);
  }

  const digest = createHash('sha256');
  for (const file of files) {
    const contents = await readFile(path.join(directory, file));
    digest.update(JSON.stringify([file, contents.length]) + '\n');
    digest.update(contents);
  }
  const version = digest.digest('hex').slice(0, 20);
  const assets = files.map((file) => `./${file.split('/').map(encodeURIComponent).join('/')}`);
  await writeFile(path.join(directory, 'sw.js'), workerSource(version, assets));
  return { version, assets };
}

function workerSource(version, assets) {
  return `/* Generated by scripts/build-offline.mjs. Changes are overwritten by npm run build. */
'use strict';
const VERSION = ${JSON.stringify(version)};
const ASSETS = ${JSON.stringify(assets, null, 2)};
const SCOPE = new URL(self.registration.scope);
const PREFIX = 'verso-offline:' + encodeURIComponent(SCOPE.href) + ':';
const CACHE = PREFIX + VERSION;
const URLS = new Set(ASSETS.map(asset => new URL(asset, SCOPE).href));
const INDEX = new URL('./index.html', SCOPE).href;

function inScope(url) {
  return url.origin === SCOPE.origin && url.pathname.startsWith(SCOPE.pathname);
}

self.addEventListener('install', event => {
  event.waitUntil((async () => {
    const cache = await caches.open(CACHE);
    // addAll is atomic: a failed asset keeps this update from replacing a
    // complete working version. Redirects cannot introduce external assets.
    await cache.addAll([...URLS].map(url => new Request(url, {
      cache: 'reload', mode: 'same-origin', redirect: 'error',
    })));
  })());
  // Let an existing version finish its sessions; never force a page reload.
});

self.addEventListener('activate', event => {
  event.waitUntil((async () => {
    const names = await caches.keys();
    await Promise.all(names.filter(name => name.startsWith(PREFIX) && name !== CACHE)
      .map(name => caches.delete(name)));
    await self.clients.claim();
  })());
});

async function navigation(request) {
  let response;
  try {
    response = await fetch(request);
    if (response.ok) return response;
  } catch { /* An installed app can open its cached entry while offline. */ }
  const cache = await caches.open(CACHE);
  return await cache.match(INDEX) || response || new Response('Verso is not available offline yet.', {
    status: 503, headers: { 'Content-Type': 'text/plain; charset=utf-8' },
  });
}

async function asset(request, key) {
  const cache = await caches.open(CACHE);
  const stored = await cache.match(key);
  if (stored) return stored;
  const response = await fetch(request);
  if (response.ok && response.type !== 'opaque' && inScope(new URL(response.url || request.url))) {
    await cache.put(key, response.clone());
  }
  return response;
}

self.addEventListener('fetch', event => {
  const request = event.request;
  if (request.method !== 'GET') return;
  const url = new URL(request.url);
  if (!inScope(url)) return;
  if (request.mode === 'navigate') {
    event.respondWith(navigation(request));
    return;
  }
  // Only the build's known static assets enter the cache, never API calls or
  // another application sharing this origin. Queries do not duplicate assets.
  url.search = '';
  url.hash = '';
  if (URLS.has(url.href)) event.respondWith(asset(request, url.href));
});
`;
}

if (process.argv[1] && path.resolve(process.argv[1]) === fileURLToPath(import.meta.url)) {
  const result = await buildOffline();
  console.log(`Offline app: ${result.assets.length} assets, version ${result.version}`);
}
